include Makefile.local
include Makefile.docker
include Makefile.deploy

.PHONY: help

help:
	@echo ""
	@echo "Local development:"
	@echo "  make local-bootstrap"
	@echo "  make local-install-backend"
	@echo "  make local-install-frontend"
	@echo "  make local-backend"
	@echo "  make local-frontend"
	@echo "  make local-worker"
	@echo "  make local-scheduler"
	@echo "  make local-seed-admin"
	@echo "  make local-dev   (optional: LOCAL_SKIP_NEXTCLOUD=1, NEXTCLOUD_WAIT_SEC=60)"
	@echo "  make local-sync-nc-bridge   (needs NEXTCLOUD_HTML_ROOT= /var/snap/nextcloud/current/nextcloud/extra-apps/)"
	@echo ""
	@echo "Docker development:"
	@echo "  make docker-dev   (optional: DOCKER_SKIP_BROWSER=1, DOCKER_WAIT_SEC=180)"
	@echo "  make docker-dev-rebuild"
	@echo "  make docker-migrate"
	@echo "  make docker-up"
	@echo "  make docker-up-detached"
	@echo "  make docker-up-rebuild"
	@echo "  make docker-up-open"
	@echo "  make docker-open-nextcloud"
	@echo "  make docker-nextcloud-up"
	@echo "  make docker-nextcloud-down"
	@echo "  make docker-down"
	@echo "  make docker-build"
	@echo "  make docker-logs"
	@echo "  make docker-ps"
	@echo "  make docker-seed-admin"
	@echo ""
	@echo "Deployment:"
	@echo "  make deploy-config"
	@echo "  make deploy-up"
	@echo "  make deploy-down"
	@echo "  make deploy-logs"
	@echo "  make deploy-seed-admin"
	@echo "  make deploy-backup-db"
	@echo "  make deploy-restore-db BACKUP_FILE=/path/to/backup.sql.gz"
