"""generate tables

Revision ID: bb074152be13
Revises: b477337986cf
Create Date: 2026-03-07 21:13:41.125913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb074152be13'
down_revision: Union[str, Sequence[str], None] = 'b477337986cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('citations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('chat_messages', 'retrieved_chunks_json')
    op.add_column('connectors', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('connectors', 'last_sync_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('documents', sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('sync_status', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('sync_error', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('owner_external_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('allowed_user_ids', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('documents', sa.Column('allowed_group_ids', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('documents', sa.Column('public_link_enabled', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('acl_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('documents', 'indexed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('documents', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('ix_documents_connector_sync_status', 'documents', ['connector_id', 'sync_status'], unique=False)
    op.create_index(op.f('ix_documents_owner_external_id'), 'documents', ['owner_external_id'], unique=False)
    op.add_column('sync_jobs', sa.Column('requested_by_id', sa.UUID(), nullable=True))
    op.add_column('sync_jobs', sa.Column('job_key', sa.String(length=255), nullable=False))
    op.add_column('sync_jobs', sa.Column('worker_task_id', sa.String(length=255), nullable=True))
    op.add_column('sync_jobs', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('sync_jobs', sa.Column('progress_total', sa.Integer(), nullable=True))
    op.add_column('sync_jobs', sa.Column('progress_completed', sa.Integer(), nullable=True))
    op.alter_column('sync_jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sync_jobs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_sync_jobs_requested_by_id'), 'sync_jobs', ['requested_by_id'], unique=False)
    op.create_unique_constraint('uq_sync_jobs_job_key', 'sync_jobs', ['job_key'])
    op.create_foreign_key(op.f('fk_sync_jobs_requested_by_id_users'), 'sync_jobs', 'users', ['requested_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('external_subject', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('nextcloud_base_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_auth_provider'), 'users', ['auth_provider'], unique=False)
    op.create_index(op.f('ix_users_external_subject'), 'users', ['external_subject'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint('uq_users_auth_provider_external_subject', 'users', ['auth_provider', 'external_subject'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_auth_provider_external_subject', 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_external_subject'), table_name='users')
    op.drop_index(op.f('ix_users_auth_provider'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'nextcloud_base_url')
    op.drop_column('users', 'username')
    op.drop_column('users', 'external_subject')
    op.drop_column('users', 'auth_provider')
    op.drop_constraint(op.f('fk_sync_jobs_requested_by_id_users'), 'sync_jobs', type_='foreignkey')
    op.drop_constraint('uq_sync_jobs_job_key', 'sync_jobs', type_='unique')
    op.drop_index(op.f('ix_sync_jobs_requested_by_id'), table_name='sync_jobs')
    op.alter_column('sync_jobs', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sync_jobs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('sync_jobs', 'progress_completed')
    op.drop_column('sync_jobs', 'progress_total')
    op.drop_column('sync_jobs', 'retry_count')
    op.drop_column('sync_jobs', 'worker_task_id')
    op.drop_column('sync_jobs', 'job_key')
    op.drop_column('sync_jobs', 'requested_by_id')
    op.drop_index(op.f('ix_documents_owner_external_id'), table_name='documents')
    op.drop_index('ix_documents_connector_sync_status', table_name='documents')
    op.alter_column('documents', 'last_seen_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('documents', 'indexed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('documents', 'acl_json')
    op.drop_column('documents', 'public_link_enabled')
    op.drop_column('documents', 'allowed_group_ids')
    op.drop_column('documents', 'allowed_user_ids')
    op.drop_column('documents', 'owner_external_id')
    op.drop_column('documents', 'sync_error')
    op.drop_column('documents', 'sync_status')
    op.drop_column('documents', 'modified_at')
    op.alter_column('connectors', 'last_sync_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('connectors', 'metadata_json')
    op.add_column('chat_messages', sa.Column('retrieved_chunks_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('chat_messages', 'citations_json')
    # ### end Alembic commands ###
